--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MulqiGaming64/SimpleStaffChat
build-by-default: true
branches:
- main
projects:
  SimpleStaffChat:
    path: ""
    icon: "icons.png"
...
