---
name: SimpleStaffChat
version: 1.0.0
main: MulqiGaming64\SimpleStaffChat\SimpleStaffChat
api: 4.0.0
author: MulqiGaming64
description: a Plugin for enable player chat in staff channel

permissions:
  simplestaffchat.use:
    description: Permission to use SimpleStaffChat Commands
    default: op
...
